/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package log4j1eg;

import org.apache.log4j.Logger;

public class App {

    private static final Logger LOGGER = Logger.getLogger(App.class);

    public String logInfo(String message) {
        LOGGER.info(message);
        return message + " logged";
    }

    public static void main(String[] args) throws InterruptedException {
        int count = 0;
        App app = new App();
        while(count < 10) {
            System.out.println(app.logInfo("message " + count));
            count++;
            Thread.sleep(1000);
        }
    }
}
